proto_library(
    name = "discovery",
    visibility = ["//envoy:__pkg__"],
    deps = [
        "//envoy/service/discovery/v2:ads",
        "//envoy/service/discovery/v2:cds",
        "//envoy/service/discovery/v2:common",
        "//envoy/service/discovery/v2:eds",
        "//envoy/service/discovery/v2:lds",
        "//envoy/service/discovery/v2:rds",
        "//envoy/service/discovery/v2:sds",
    ],
)
