load("//bazel:api_build_system.bzl", "api_proto_library")

licenses(["notice"])  # Apache 2

api_proto_library(
    name = "fault",
    srcs = ["fault.proto"],
    visibility = ["//envoy/api/v2/filter:__subpackages__"],
)
